<?php

namespace Ahe\gsbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComptableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComptableRepository extends EntityRepository
{
    
    
	public function findByLoginAndMdp($login, $mdp) {
        $queryBuilder = $this->createQueryBuilder('Comptable') ;
        $queryBuilder-> where('Comptable.login = :login') 
                        ->setParameter('login', $login)
                     ->andWhere ('Comptable.mdp = :mdp')
                        ->setParameter('mdp',$mdp) ;
        $result = $queryBuilder->getQuery()->getOneOrNullResult() ;
         
        return $result ;
    }
}
